languageCode = 'en-us'
title = 'Novasredes'

# To allow Hugo to read `.git`
enableGitInfo = true

relativeUrls = true

[params]
	tagline = 'Redes de computadores experimentais'
	copyright = 'Copyright everything by Tristan Brice Velloza Kildaire'
	license = 'Creative Commons Attribution-ShareAlike 4.0 International'
	logoPath = 'standard/logo.png'
